#!/usr/bin/env bash
#
# BSD 3-Clause License
#
# Copyright (c) Circuit Blvd., Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#set up parameters
echo "***********************************************************"
echo "MY_POD_NAME="$MY_POD_NAME
echo "MY_POD_IP="$MY_POD_IP
idx=$(echo $MY_POD_NAME | awk -F- '{print $NF}')

didx=$DIDX
vidx=$(($idx+1))
mp4src="/mp4-"$vidx
nginx_port=$((8080 + $idx))
rtmp_port=$((1935 + $idx))

didxn=$(printf "%d" "'$didx")
nextn=$(($didxn +$idx))
didxme=$(awk -v a="$nextn" 'BEGIN{printf "%c", a}')
bdev="/dev/vd"$didxme
m="/mnt/vhosts/vd"$didxme

echo "block device="$bdev
echo "mnt point="$m

#copy movies and thumbnails from a movie depot. We assume it is /tmp/mm in this example
echo
echo "****************Copying movies and thumbnails****************"
mkdir -p $m/mp4/
cp -r /tmp/mm/$mp4src/* $m/mp4/
echo "***Movies copied****************"
ls $m/mp4
echo "***Thumbnails copied************"
ls $m/mp4/img/
echo "Done!"

echo
echo "****************Making html dirs and files****************"
ln -s $m/mp4/ /var/www/html/mp4s
cp /var/www/html/js/advanced-$vidx.js /var/www/html/js/advanced.js 
echo "advanced-$vidx.js copied"
echo "Done!"

echo
echo "****************Launching nginx****************"
#ip_addr=$(ifconfig | grep "10.12.90" | awk '{print $2}')
ip_addr=$MY_POD_IP
echo $ip_addr":"$nginx_port" rtmp:"$rtmp_port
sed -i "s/8080/$nginx_port/" /usr/local/nginx/conf/nginx.conf
sed -i "s/1935/$rtmp_port/" /usr/local/nginx/conf/nginx.conf

# start nginx web server
/usr/local/nginx/sbin/nginx

sleep infinity
